### ISSUE TITLE
Tests fail on RedHat-like systems

### ISSUE THREAD

**Issue by eserte** [athreef/Alien-libpid#1]
On RedHat-like systems (CentOS6, CentOS7, Fedora28) the test suite fails:
```
# Failed test 'xs'
# at t/init.t line 10.
#   ExtUtils::CBuilder->compile failed
#     error building testalienMo3Lz/test.o from 'testalienMo3Lz/test.c' at /opt/perl-5.28.0/lib/5.28.0/ExtUtils/CBuilder/Base.pm line 185.
#     cc -I/opt/perl-5.28.0/lib/5.28.0/x86_64-linux/CORE -fPIC -c -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -o testalienMo3Lz/test.o testalienMo3Lz/test.c
#     testalienMo3Lz/test.xs:5:20: fatal error: libpid.h: No such file or directory
#      #include <libpid.h>
#                         ^
#     compilation terminated.
t/init.t ............... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```

**Comment by a3f** [comment]
Hi there, first a belated thanks for taking the time to open the issue!
I
Problem is two-fold, first Alien::Build doesn't gather *.pc files in `$prefix/lib64` and second, the projects I package as Alien modules don't install their *.pc into `$prefix/lib64` anyway, they do into `$prefix/lib`, which in turn isn't in pkg-config's `pc_path` on Fedora/CentOS/RHEL.

For the former, I've opened https://github.com/Perl5-Alien/Alien-Build/pull/72. For the latter one, I'll patch the projects which CMakeLists.txt I had written. I'll prepare a new release for all the affected modules when there's an Alien::Build release to track.

Thanks again!
